"""Independent exact checks for the pure same-row valuative theorem.

Logical status: diagnostic only.  The paper proof is the basis-matrix argument
and the row-occupancy rectangle inequality.  This script checks that no sign,
transpose, or small combinatorial case was copied incorrectly.

All linear ranks are computed over QQ using fractions.  All rectangle maxima
are exhaustive integer counts; no random sampling or finite field is used.
"""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from itertools import combinations
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "n5_orbit1_WM_same_row_valuative_small_lemmas_QQ_exact.json"
N = 5


def rank_q(rows: list[list[int]]) -> int:
    matrix = [[Fraction(value) for value in row] for row in rows if any(row)]
    if not matrix:
        return 0
    rank = 0
    for column in range(len(matrix[0])):
        pivot = next(
            (index for index in range(rank, len(matrix)) if matrix[index][column]),
            None,
        )
        if pivot is None:
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        scale = matrix[rank][column]
        matrix[rank] = [value / scale for value in matrix[rank]]
        for index in range(len(matrix)):
            if index == rank or not matrix[index][column]:
                continue
            scale = matrix[index][column]
            matrix[index] = [
                left - scale * right
                for left, right in zip(matrix[index], matrix[rank])
            ]
        rank += 1
    return rank


def variable(row: int, column: int) -> int:
    return N * row + column


def lemma_21_rows() -> list[list[int]]:
    """Equations saying BA is symmetric for every B in Sym^2_off(QQ^5)."""
    rows: list[list[int]] = []
    for first, second in combinations(range(N), 2):
        b = [[0] * N for _ in range(N)]
        b[first][second] = b[second][first] = 1
        for i, j in combinations(range(N), 2):
            row = [0] * (N * N)
            for k in range(N):
                row[variable(k, j)] += b[i][k]
                row[variable(k, i)] -= b[j][k]
            rows.append(row)
    return rows


def lemma_22_rows() -> list[list[int]]:
    """Equations AS+SA^T=0 for every S in Sym^2_off(QQ^5)."""
    rows: list[list[int]] = []
    for first, second in combinations(range(N), 2):
        s = [[0] * N for _ in range(N)]
        s[first][second] = s[second][first] = 1
        for i in range(N):
            for j in range(i, N):
                row = [0] * (N * N)
                for k in range(N):
                    row[variable(i, k)] += s[k][j]
                    row[variable(j, k)] += s[i][k]
                rows.append(row)
    return rows


def rectangles(cells: frozenset[tuple[int, int]]) -> int:
    rows = [set() for _ in range(N)]
    for row, column in cells:
        rows[row].add(column)
    return sum(
        len(common) * (len(common) - 1) // 2
        for first, second in combinations(range(N), 2)
        if len(common := rows[first] & rows[second]) >= 2
    )


def maxima_with_base(base: frozenset[tuple[int, int]], additions: range):
    available = tuple(
        (row, column)
        for row in range(N)
        for column in range(N)
        if (row, column) not in base
    )
    result = []
    for number in additions:
        best = -1
        maximizers = []
        for extra in combinations(available, number):
            cells = base | frozenset(extra)
            value = rectangles(cells)
            if value > best:
                best = value
                maximizers = [extra]
            elif value == best:
                maximizers.append(extra)
        result.append(
            {
                "added_cells": number,
                "maximum_rectangles": best,
                "maximizer_count": len(maximizers),
                "unique_maximizer": (
                    [list(cell) for cell in maximizers[0]]
                    if len(maximizers) == 1
                    else None
                ),
            }
        )
    return result


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def main() -> None:
    rank21 = rank_q(lemma_21_rows())
    rank22 = rank_q(lemma_22_rows())
    assert rank21 == 24  # one-dimensional kernel, generated by I_5
    assert rank22 == 25  # zero kernel

    m = frozenset((0, column) for column in range(4))
    same = m | {(1, 0)}
    distinct = same | {(1, 1)}

    generic_records = maxima_with_base(m, range(0, 6))
    same_records = maxima_with_base(same, range(0, 6))
    distinct_records = maxima_with_base(distinct, range(0, 5))

    assert [record["maximum_rectangles"] for record in generic_records] == [
        0,
        0,
        1,
        3,
        6,
        6,
    ]
    assert [record["maximum_rectangles"] for record in same_records] == [
        0,
        1,
        3,
        6,
        6,
        10,
    ]
    assert [record["maximum_rectangles"] for record in distinct_records] == [
        1,
        3,
        6,
        6,
        10,
    ]
    assert same_records[-1]["maximizer_count"] == 1
    assert distinct_records[-1]["maximizer_count"] == 1

    result = {
        "status": "PASS_EXACT_QQ_AND_INTEGER_DIAGNOSTIC",
        "evidence_class": "exact characteristic-zero and exhaustive integer diagnostic",
        "logical_scope": (
            "Checks Lemmas 2.1 and 2.2 and the small rectangle maxima only; "
            "the pure proof does not depend on this file."
        ),
        "lemma_2_1": {
            "unknowns": 25,
            "rank_over_QQ": rank21,
            "kernel_dimension": 25 - rank21,
            "claimed_kernel": "QQ * I_5",
        },
        "lemma_2_2": {
            "unknowns": 25,
            "rank_over_QQ": rank22,
            "kernel_dimension": 25 - rank22,
        },
        "rectangle_maxima": {
            "base_M": generic_records,
            "same_endpoint_base_M_plus_x10": same_records,
            "distinct_endpoint_base_M_plus_x10_x11": distinct_records,
        },
        "script_sha256_before_output_write": sha256(Path(__file__)),
    }
    OUTPUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(result["status"])
    print(f"lemma_2_1_rank_QQ={rank21}")
    print(f"lemma_2_2_rank_QQ={rank22}")
    print("same_endpoint_maxima=0,1,3,6,6,10")
    print("distinct_endpoint_maxima=1,3,6,6,10")


if __name__ == "__main__":
    main()
